spring.datasource.url=jdbc:postgresql://localhost:5431/wasabi
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

spring.application.name=wasabi-backend

jwt.secretKey = 5H1U+tPzpMLiMUGZCaGDa2weBFnBUjxwCuprYGss2J8=