spring.datasource.url=jdbc:postgresql://localhost:5431/wasabi
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

spring.application.name=wasabi-backend

cloudinary.cloud-name=drrcsqhci
cloudinary.api-key=971316223892533
cloudinary.api-secret=GWV_hJTu4c9uK5Uu8l7leKiymt8

jwt.secretKey = 5H1U+tPzpMLiMUGZCaGDa2weBFnBUjxwCuprYGss2J8=